
// carousel
$(document).ready(function(){
    $('.owl-1').owlCarousel({
        loop:true,
        margin:20,
       items:5,
       dots:true,
       dotsEach:true,
       responsive:{
        0:{
            items:1,
        },
        600:{
            items:3,
        },
        1000:{
            items:5,
        }
    }
    })
  });
  $(document).ready(function(){
    $('.owl-2').owlCarousel({
        loop:true,
        margin:20,
       items:4,
       dots:true,
       dotsEach:true,
       responsive:{
        0:{
            items:1,
        },
        600:{
            items:3,
        },
        1000:{
            items:5,
        }
    }
    })
  });